### ISSUE TITLE
development environment

### ISSUE THREAD

**Issue by achang6** [achang6/wallstory#3]
For the sake of support as well as to learn about the fabled Linux OS; I have decided to wipe my Windows 8 laptop and install the Linux OS. 

Currently I am backing up/moving/ saving/ jumping ship. It will take approximately 4 hours more until I am ready to leave Windows (at least on my laptop lol). 

I will begin my search for Ubuntu to burn to a disk as well as support for the betrayal of Windows during this time. I will also search for an Advil tablet or something... this weather is killing me....

At the same time I might as well download virtualbox onto my desktop loaded with Windows 7 as a backup. I must remember to pickup the Ubuntu image that was saved onto my student account at the university. This means... a flash drive? Yeah I should bring one to class. 

I need coffee  ~(O.O)~

**Comment by achang6** [comment]
Make that 8 hours.

**Comment by achang6** [comment]
Successfully ripped Windows 8 from my laptop. With its remains in some ditch, I proudly have a penguin in my bag. 

I mean I installed Ubuntu onto my laptop.

**Comment by bdhhtb** [comment]
Closing this Issue so I can naively use `has_open_issues` as a check on project status
