### ISSUE TITLE
Add to README.md

### ISSUE THREAD

**Issue by bdhhtb** [achang6/wallstory#5]
Include instructions on how to run your game

**Comment by achang6** [comment]
Pencil and paper atm. Will conceive the game once my python comes of age. In general just find mainwall.py (TBC) and run 'python mainwall.py' from terminal. idk how it runs w/ Windows/Macs though. Actually is the pygame module necessary >.>?

**Comment by bdhhtb** [comment]
Just get something runnable up here. It doesn't have to be elegant :)

**Comment by achang6** [comment]
I don't want this:
'Elegance not included'
on my project Q.Q

Working as fast as possible. 
The general frame is ready, but functionality and pretty lights are not available.

**Comment by bdhhtb** [comment]
What about "retrofitted for elegance" ?
